FROM anapsix/alpine-java
MAINTAINER fatih.cayir@accenture.com
WORKDIR /data
EXPOSE 8080
COPY samplemicroservice.jar /data/samplemicroservice.jar
ENTRYPOINT ["java"]
CMD ["-jar","/data/samplemicroservice.jar"]
EXPOSE 8080
 


